### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by DelphiDv** [OtakuMegane/DerpyBot#11]
I get this weird error every few hours or so when i run the bot. When i get this error it forces me to manually re run the bot manually.

https://hastebin.com/zuqejatuyu.sql

**Comment by OtakuMegane** [comment]
Check which version of discord.py you currently have. Looks like some versions before 1.2.5 had an issue with handling emoji reactions: https://github.com/Rapptz/discord.py/issues/2422

Managed to trigger the error you got under 1.2.4 but with 1.2.5 it didn't occur.
