### ISSUE TITLE
bot unable to send discord messages / crash

### ISSUE THREAD

**Issue by ineptvirus** [OtakuMegane/DerpyBot#3]
Firstly, sorry OtakuMegane for opening a load of issues in the past few days.

Anyway, The issue I'm having is the bot crashes when attempting to send a message to the discord. The bot loads up fine, enters command mode, and waits. I have set my respond rate to 100 and artificially fed it lots of text in lines.txt to give it something to play with. I've also turned off "random_on_key_fail = false" to true in an attempt to get more messages that I can verify it works. I can message the chat with the bot in and nothing is said. I have to type something in the open console (literally any command, in the below example I dont even type anything I just hit enter. This seems to prompt the bot to update the console and also attempt to send a message (which it forms just fine), however I never see the message in the server and the bot immediately goes offline as if it has crashed. No message in cinsole to verify crash. console example below:

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\derpybot.py =====
[DerpyBot] DerpyBot version 0.9.3.4
[DerpyBot] Loading markov...
[DerpyMarkov] Loading DerpyMarkov...
[DerpyMarkov] DerpyMarkov version 0.9.3.4
[DerpyMarkov] I know 125 lines containing a total of 874 words.
[DerpyMarkov] 454 of those words are unique.
[DerpyMarkov] We are currently using a state size of 1 which generated 455 contexts.
[DerpyMarkov] Normal reply rate is 100.0 and bot name reply rate is 100.0.
[DerpyBot] Loading chat client...
[Discord]  We have logged in to Discord!
[Discord]   Name: Mirai
[Discord]   ID: 417657851587330051
[Discord]   Playing: with AI
[DerpyBot] Entering command mode...
>> 
[Discord] Message from #vault: I think it works now>> 

[Discord] Message to #vault: I'm bad at coping with all the guy who plays jean valjean in 10 minutes, and I wanna do but i know what are you yet. That I have about an ADL suggestion, Plan my boring ass course[DerpyMarkov] Saving lines...>> 
```
If I type in further commands it seems to respond to them badly but does run them. However the discord side of the bot is rather dead still.

```
shutdown
[Discord] Message from #vault: it should do anyway[DerpyMarkov] Lines saved![DerpyBot] Shutting everything down...


[Discord] Message to #vault: And I'm bad at coping with it is home[DerpyMarkov] DerpyMarkov is shutting down now.

[Discord] Message from #vault: it will have to learn for a while yet even though I gave it a couple hundred messages[Discord] Logging out...

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\clients\discord_client\discord_client.py", line 74, in on_message
    reply = markov.incoming_message(message.clean_content, discord_client.user.name, markov_learn)
  File "C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\modules\derpymarkov\markov.py", line 165, in incoming_message
    learn(prepared_message)
  File "C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\modules\derpymarkov\markov.py", line 292, in learn
    parsed_sentences = list(model.generate_corpus(text))
NameError: name 'model' is not defined
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 450, in sock_connect
    return (yield from fut)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\clients\discord_client\discord_client.py", line 84, in on_message
    await discord_client.send_message(message.channel, reply)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
[Discord] We are logged out now!
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 555, in __iter__
    resp = yield from self._coro
[Discord] Shutting down client...
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
[DerpyBot] Good night!
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\async_timeout\__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
>>>   File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\async_timeout\__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.4\clients\discord_client\discord_client.py", line 84, in on_message
    await discord_client.send_message(message.channel, reply)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 555, in __iter__
    resp = yield from self._coro
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

```

**Comment by OtakuMegane** [comment]
No worries about the issues, the script has mostly been in personal use so there's sure to be bugs I missed. This one seems a bit trickier though. Since the script did still respond to commands and was able to complete the shutdown process I'm not sure anything in the script itself was hung or crashed.

At least the first error (NameError: name 'model' is not defined) is due to attempting to process a message during shutdown. I've done another fix that should avoid that, it's included in the [v0.9.3.5 release](https://github.com/OtakuMegane/DerpyBot/releases/tag/v0.9.3.5).

Try running it again and see if it behaves differently. If it doesn't respond properly for a couple minutes, try using shutdown again and post any errors here.

**Comment by ineptvirus** [comment]
Running new version now. I started up the script and pinged a message into the discord channel. I couldn't see anything in console, so I hit enter and it showed the message I had sent. Another enter hit revealed the "message to #vault" log and the bot successfully sent a message into the discord channel and it didn't crash.
However, I sent a two more messages into the channel, and had to press enter for them to be seen in the console. The bot attempted to send a second message but it was never seen on the discord channel, and the bot went offline. The shutdown command was accepted but seemed to behave a little differently, displaying a non-standard shutdown message series.

I think there might be two seperate issues - 1. bot crash on message send (or perhaps message save?), and 2. discord messages do not show in the console unless prompted, by either hitting enter or sending a command (and therefore hitting enter).

Also note, it did not manage to save any messages to lines.txt, perhaps this is where is crashed?

```
==== RESTART: C:\Users\menja01\Desktop\bot\DerpyBot-v0.9.3.5\derpybot.py ====
[DerpyBot] DerpyBot version 0.9.3.5
[DerpyBot] Loading markov...
[DerpyMarkov] Loading DerpyMarkov...
[DerpyMarkov] DerpyMarkov version 0.9.3.5
[DerpyMarkov] I know 12 lines containing a total of 169 words.
[DerpyMarkov] 108 of those words are unique.
[DerpyMarkov] We are currently using a state size of 1 which generated 109 contexts.
[DerpyMarkov] Normal reply rate is 100.0 and bot name reply rate is 100.0.
[DerpyBot] Loading chat client...
[Discord]  We have logged in to Discord!
[Discord]   Name: Mirai
[Discord]   ID: 417657851587330051
[Discord]   Playing: with AI
[DerpyBot] Entering command mode...
>> 
[Discord] Message from #vault: Testing>> 

>> 
>> 
[DerpyMarkov] Saving lines...[Discord] Message from #vault: <@417657851587330051> test>> 


[DerpyMarkov] Lines saved!>> 

>> 
>> 
[Discord] Message from #vault: Gotta spam this shit, goddamn>> 

[Discord] Message to #vault: This seems to 100 and waits.>> 

[DerpyMarkov] Saving lines...[Discord] Message from #vault: YES>> 


[DerpyMarkov] Lines saved![Discord] Message from #vault: IT LIVES>> 


[Discord] Message to #vault: I never see the lazy brown fox jumped over the message the below example I just fine), however I have set my respond rate to prompt the message the message the console and artificially fed it something to play with.[DerpyMarkov] Saving lines...>> 


[DerpyMarkov] Lines saved!>> 

>> 
>> shutdown
[DerpyBot] Shutting everything down...
[DerpyMarkov] DerpyMarkov is shutting down now.
[Discord] Logging out...

shutdown
```

Let me know if you want me to try anything to help you out

Edit: I'm fairly sure the bot crashes when saving text. I managed to get the bot to save text successfully, but afterwards the bot went offline. No message was attempted by the bot so I dont think its the sending which is crashing it, but instead the saving. Have another log which seems to confirm this:

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\menja01\Desktop\bot\DerpyBot-v0.9.3.5\derpybot.py ====
[DerpyBot] DerpyBot version 0.9.3.5
[DerpyBot] Loading markov...
[DerpyMarkov] Loading DerpyMarkov...
[DerpyMarkov] DerpyMarkov version 0.9.3.5
[DerpyMarkov] I know 17 lines containing a total of 179 words.
[DerpyMarkov] 116 of those words are unique.
[DerpyMarkov] We are currently using a state size of 1 which generated 117 contexts.
[DerpyMarkov] Normal reply rate is 100.0 and bot name reply rate is 100.0.
[DerpyBot] Loading chat client...
[Discord]  We have logged in to Discord!
[Discord]   Name: Mirai
[Discord]   ID: 417657851587330051
[Discord]   Playing: with AI
[DerpyBot] Entering command mode...
>> 
[Discord] Message from #vault: Try again>> 

>> 
[DerpyMarkov] Saving lines...>> 
shutdown
[DerpyMarkov] Lines saved![DerpyBot] Shutting everything down...

[DerpyMarkov] DerpyMarkov is shutting down now.
[Discord] Logging out...
```

**Comment by OtakuMegane** [comment]
At least we seem to be rid of the messy error messages. It does appear to be having issues with the learning and/or saving routines. A few things to check which should narrow down the cause further:
 - If you changed the `save_interval` what is it currently set to? It shouldn't need to be less than 60.
 - Run the script and check the CPU usage as it processes a message. It will spike briefly when the markov chain kicks in (which is normal) but shouldn't be more than a second or two.
 - Once you've done that, in the derpymarkov config under `[General]` set `learn = false` and try it again.
 - If after disabling learning the problem seems to go away, replace the `markov.py` file in derpymarkov with [this markov.py](https://dl.dropbox.com/s/6s3xfospy0x6ujs/markov.py), then set `learn = true` and give it one more run.

Somewhere in the process things should start working and we'll have an idea what the root problem is. Unless more error messages pop up in the console you won't need to post any logs here, just report back the results of testing.

**Comment by ineptvirus** [comment]
I've done some more testing, with the following test notes I wrote along the way:

```
first run with save interval changed to 30 to 60:
message sent to discord from me. no console response.
wait 60
hit enter in console. message appears in console.
hit enter again. bot is gone from server.
shutdown command given. got posts in console an attemtped message to the server but it rever arrives. Bot seems to save given discord lines and shuts down. Save seems successful. No observed CPU spikes.

changed learn to false
send message to channel again. no response.
Hit enter in console. message is recieved from bot.
wait maybe half a min. bot goes offline.
wait half a min again. hit enter. bot is still offline in discord, but console shows it trying to send a message to the channel.
"client status" command given. Bot returns true.

new maykov.py file used
bot opens and starts ok. bot online
message sent to channel, no visible reponse
wait 2 min, bot goes offline
press the in console. channel message appears in console.
enter
enter
enter
shutdown given. bot shuts down

changed learn back to true
run bot. bot online
wait 10 min, bot still online
sent message to channel, hit enter. message appears in console, bot online
repeat sending message, hit enter and message appears in console along with saving lines message.
repeat sending message, hit enter and message appears in console
hit enter, new line
hit enter, new line
bot still online
new message, hit enter. appears in console and saves lines.
bot still online
messaged channel again. hit enter. bot started save. bot received message from general. bot finished saving. bot attempted to send a message to the server, then goes offline
```
I'm really at a loss what is causing it to crash, sometimes it sticks around for a while, and sometimes it crashes pretty quickly. The bot has never managed to successfully send a message to the server apart from the one time in a previous response so perhaps it crashes when attempting to send it. This is the console from my final log, from the above final test

```
===== RESTART: C:\Users\Jake\Desktop\Mirai\DerpyBot-v0.9.3.5\derpybot.py =====
[DerpyBot] DerpyBot version 0.9.3.5
[DerpyBot] Loading markov...
[DerpyMarkov] Loading DerpyMarkov...
[DerpyMarkov] DerpyMarkov version 0.9.3.5
[DerpyMarkov] I know 127 lines containing a total of 886 words.
[DerpyMarkov] 459 of those words are unique.
[DerpyMarkov] We are currently using a state size of 1 which generated 460 contexts.
[DerpyMarkov] Normal reply rate is 100.0 and bot name reply rate is 100.0.
[DerpyBot] Loading chat client...
[Discord]  We have logged in to Discord!
[Discord]   Name: Mirai
[Discord]   ID: 417657851587330051
[Discord]   Playing: with AI
[DerpyBot] Entering command mode...
>> 
[Discord] Message from #general: test again gah>> 

>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
>> 
[DerpyMarkov] Saving lines...[Discord] Message from #general: test#>> 


[DerpyMarkov] Lines saved![Discord] Message from #general: test>> 


[Discord] Message from #general: test>> 

>> 
>> 
>> 
>> 
>> 
[DerpyMarkov] Saving lines...[Discord] Message from #general: again>> 


[DerpyMarkov] Lines saved![Discord] Message to #general: It changes your default playback again>> 


>> 
>> 
>> shutdown
[DerpyBot] Shutting everything down...
[DerpyMarkov] DerpyMarkov is shutting down now.
[Discord] Logging out...
```

**Comment by OtakuMegane** [comment]
Yeah I'm running out of possibilities in the script. Just to be sure, are you running this from a computer at home or on some form of remote host/server?

Two more things to try:
 - When the bot finishes starting up, before typing any other messages issue the command `!derpy uptime`  in the chat and see if it responds. (Assuming you didn't change the command_alias). If it does, enter a regular message in chat, then issue the command again to see if it still responds.
 - In the discord config, set `use_markov = false` then try another run. This will take the markov module out of the picture entirely.

**Comment by ineptvirus** [comment]
I'm getting confused because I cant locate what is causing the crash. However, I have never had the bot auto-update the console with new messages, no matter how long I wait. I have to press enter to get the console to see the new message, then enter again to get the bot to send a message. Is this the way it is intended? Perhaps the problem is linked?

**Comment by ineptvirus** [comment]
So I remade the bot again, filled in all the configs from new and changed only the minimal amount of things (token, channel etc) and it seems to be okay right now. ive had it running and talking for about an hour so far, no crashes. I still need to hit enter in the console to prompt it to do anything but it seems to have stopped crashing. As far as I can tell, the save-interval is one of the only things that is different, back to 900 now but I havent saw it save yet which strikes me as odd. Also I set reply rate to 50, and random_on_key_fail back to standard, false. Owner ID I have left at 0.

**Comment by ineptvirus** [comment]
It works when I run it from a python shortcut with an argument to go to your bot, but not if I run it from cmd. oh well. Works now anyway. Odd.

**Comment by OtakuMegane** [comment]
Glad to know you eventually got it working. I'm still at a loss as well on what was wrong but will keep all this in mind in case I do encounter something later. If these problems occur again you can re-open this issue and let me know.

To answer a couple things for you...
The console messages are just printed for convenience, they don't affect sending or receiving messages.

When working properly, everything should run without intervention including the console updating.

The `save_interval` is in seconds and is a timed event; in the case of being set to 900, it'll do a save every 15 minutes if learning is on and it has added new content during that period. If learning is off or the messages it receives don't come from a source listed in `markov-channels`, it won't have anything new to save.
