### ISSUE TITLE
Exception in thread Thread-2:

### ISSUE THREAD

**Issue by clockwork04** [OtakuMegane/DerpyBot#4]
Really sorry if its me doing something dumb but ive come across this error which by my best efforts i cant fix, any help is really appreciated because so far this is the only bot ive been able to find that does this 

Error
![py_2018-10-09_18-38-00](https://user-images.githubusercontent.com/9094379/46702814-95c46380-cbf2-11e8-9e84-14e9c9db0961.png)

System Specs:
![inkedapplicationframehost_2018-10-08_19-57-56_li](https://user-images.githubusercontent.com/9094379/46702873-d623e180-cbf2-11e8-8081-14f3c2b8af3a.jpg)

Python Version:
![pythonw_2018-10-09_18-41-43](https://user-images.githubusercontent.com/9094379/46702928-14b99c00-cbf3-11e8-9377-56dec98bb69b.png)

Edit: here it is with Markov disabled in config.py
![cmd_2018-10-09_18-51-00](https://user-images.githubusercontent.com/9094379/46703297-77f7fe00-cbf4-11e8-87df-6a42d4268c90.png)

**Comment by OtakuMegane** [comment]
This one isn't your fault. It is apparently due to a difference in how get_event_loop works prior to Python 3.5.3. Added a small fix in [v0.9.3.7](https://github.com/OtakuMegane/DerpyBot/releases/tag/v0.9.3.7) that should take care of the problem.
