### ISSUE TITLE
file: '<string>', line: 1 error

### ISSUE THREAD

**Issue by snaildos** [OtakuMegane/DerpyBot#6]
I get a error when running bot:
n 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = SafeConfigParser(allow_no_value = True)
[DerpyBot] DerpyBot version 0.9.3.7
[DerpyBot] Loading markov...
[DerpyMarkov] Loading DerpyMarkov...
[DerpyMarkov] DerpyMarkov version 0.9.3.9
[DerpyMarkov] I know 1 lines containing a total of 1 words.
[DerpyMarkov] 1 of those words are unique.
[DerpyMarkov] We are currently using a state size of 1 which generated 2 contexts.
[DerpyMarkov] Normal reply rate is 2.0 and bot name reply rate is 100.0.
[DerpyBot] Loading chat client...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\folders\chatbot\DerpyBot\clients\discord_client\discord_client.py", line 116, in launch
    discord_commands.load_custom_commands(False, parent_location)
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\folders\chatbot\DerpyBot\clients\discord_client\discord_commands.py", line 71, in load_custom_commands
    config.read_string(commands_input)
  File "C:\Python37\lib\configparser.py", line 722, in read_string
    self.read_file(sfile, source)
  File "C:\Python37\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "C:\Python37\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1
'derp'

**Comment by OtakuMegane** [comment]
Found the problem, it wasn't properly handling the commands file being empty or having no sections. v0.9.3.8 should have this fixed.

**Comment by snaildos** [comment]
Problem solved! But what is the bot supposed to do? I thought its a chat bot, when chatting to it, it only logs messages in CMD, what do I do to setup?
Also getting error:
[Discord Client] Discord Client version 0.9.2.9
[Discord Client]  We have logged in to Discord!
[Discord Client]   Name: testing bot
[Discord Client]   ID: 574097225337012225
[Discord Client]   Could not set 'Playing' status for some reason.
[Discord Client]
Witch is OK, but like to have the playing working.

**Comment by ineptvirus** [comment]
The latest release seems to be sending no messages to discord with no error messages @snaildos , it is meant to be sending but I will make a new issue thread for this for you since I have it also

**Comment by OtakuMegane** [comment]
The playing status will at times not set, it seems to be a Discord thing that happens at random. Have never been able to figure out why or if there is a fix.

If you've just set it up, you probably have an empty or almost-empty dictionary. It should be learning from incoming messages and (depending on settings) sometimes reply based on what it has learned before. Unfortunately it can take a while for there to be enough information for it to work with and if it can't generate a reply it won't say anything (originally it would just parrot back the message which was annoying people). I do need to work on documentation to explain a bunch of this stuff.

Check in `derpymarkov/dictionaries` and verify there's something in the file there; if so, it is learning. Something I've used for testing is to pick a single word and make up a few sentences containing the word when chatting with the bot. Usually if I then give it the single keyword directly it will reply.

**Comment by snaildos** [comment]
Ah ok, I see, I will just keep it running on my main server and just wait till it learns, THANXS!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by snaildos** [comment]
Yes, Was seeing that @ineptvirus
Getting also a error on DM
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\discord\client.py", line 242, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\folders\derpbot\DerpyBot\clients\discord_client\discord_client.py", line 88, in on_message
    if message.channel.is_private:
AttributeError: 'DMChannel' object has no attribute 'is_private'
[Discord Client] Direct Message from Zara: Helloo?
